// A sample system so first-time visitors see what Orrery does. Summaries are paraphrased.
const P = (id, title, author, year, venue, arxiv, abstract, relevance, field, why) =>
  ({ id, title, authors: [author], etal: true, year, venue, arxiv, url: `https://arxiv.org/abs/${arxiv}`, abstract, notes: '', ai: { relevance, field, why } });

export const DEMO = {
  demo: true,
  view: 'relevance',
  question: 'Can retrieval make small language models reason reliably?',
  workings: 'Hypothesis: a model under 3B parameters, given well-chosen retrieved passages, can match a 10x larger model on multi-hop reasoning. Plan: fine-tune a small model with retrieval in the loop plus self-critique, evaluate on HotpotQA-style tasks, and track where in the context the supporting evidence sits.',
  papers: [
    P('d1', 'Attention Is All You Need', 'Ashish Vaswani', 2017, 'NeurIPS', '1706.03762', 'Sequence models of the time relied on recurrence or convolution. This paper introduces the Transformer, an architecture built entirely on attention. It trains in parallel and reaches new state-of-the-art results on English-German and English-French machine translation at a fraction of the training cost. The model also transfers well to English constituency parsing.', 0.16, 'Foundations', 'The architecture every model in this system is built on — background, not evidence.'),
    P('d2', 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks', 'Patrick Lewis', 2020, 'NeurIPS', '2005.11401', 'Large language models store knowledge in their weights, but struggle to update it or show where an answer came from. RAG pairs a pre-trained sequence-to-sequence generator with a dense vector index of Wikipedia that a neural retriever searches at answer time. Two variants are compared: one conditions on the same passages for the whole output, the other can switch passages per token. RAG sets new state-of-the-art results on three open-domain QA benchmarks and produces more specific, diverse and factual text than a parametric-only baseline.', 0.86, 'Retrieval', 'The baseline recipe your study modifies: retrieve, then generate.'),
    P('d3', 'Chain-of-Thought Prompting Elicits Reasoning in Large Language Models', 'Jason Wei', 2022, 'NeurIPS', '2201.11903', 'Large language models often fail at multi-step reasoning when asked for an answer directly. The authors show that including a few worked examples with intermediate reasoning steps in the prompt, a chain of thought, sharply improves arithmetic, commonsense and symbolic reasoning. The benefit emerges only at sufficient model scale. With just eight exemplars, a 540B-parameter model reached state-of-the-art accuracy on the GSM8K math word problem benchmark.', 0.7, 'Reasoning', 'Defines the reasoning behaviour you want small models to reproduce.'),
    P('d4', 'Improving Language Models by Retrieving from Trillions of Tokens', 'Sebastian Borgeaud', 2021, 'ICML', '2112.04426', 'RETRO conditions a language model on chunks of text retrieved from a database of trillions of tokens, chosen by similarity to the text being generated. A frozen BERT retriever finds neighbours and chunked cross-attention feeds them into the model. With roughly 25 times fewer parameters, RETRO performs comparably to much larger models such as GPT-3 on the Pile. The authors also show that existing pre-trained transformers can be retrofitted with retrieval.', 0.72, 'Retrieval', 'Direct evidence that retrieval can stand in for parameters — but at pre-training time.'),
    P('d5', 'Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection', 'Akari Asai', 2023, 'ICLR', '2310.11511', 'Retrieving a fixed number of passages for every query can hurt a model when the passages are irrelevant. Self-RAG trains a single model to decide when to retrieve, and to critique both the retrieved passages and its own output using special reflection tokens. Because the reflection tokens are generated, the model\'s behaviour can be tuned at inference time. Self-RAG models outperform strong retrieval-augmented baselines on open-domain QA, reasoning and fact verification, and improve factuality and citation accuracy in long-form generation.', 0.95, 'Retrieval', 'Closest to your plan: retrieval in the loop with self-critique.'),
    P('d6', 'Toolformer: Language Models Can Teach Themselves to Use Tools', 'Timo Schick', 2023, 'NeurIPS', '2302.04761', 'Language models are strong at text but weak at simple tasks like arithmetic or looking up facts. Toolformer learns, with only a handful of demonstrations per tool, when to call external APIs, which arguments to pass and how to use the results. Tools include a calculator, a question-answering system, search engines, a translator and a calendar. The approach improves zero-shot performance across tasks, often matching much larger models, without losing core language modelling ability.', 0.38, 'Agents & tools', 'Treats retrieval as one tool among many; relevant to deciding when to retrieve.'),
    P('d7', 'Textbooks Are All You Need', 'Suriya Gunasekar', 2023, 'arXiv', '2306.11644', 'phi-1 is a 1.3B-parameter language model for code, far smaller than competing models. It was trained on a small, carefully filtered set of textbook-quality web data plus synthetic textbooks and exercises generated by a larger model. Despite its size and short training run, phi-1 reaches competitive pass rates on the HumanEval and MBPP coding benchmarks. The results argue that data quality can substitute for scale.', 0.58, 'Small models', 'Shows data quality can close the gap for small models — a rival explanation to retrieval.'),
    P('d8', 'Dense Passage Retrieval for Open-Domain Question Answering', 'Vladimir Karpukhin', 2020, 'EMNLP', '2004.04906', 'Open-domain question answering traditionally used sparse keyword retrieval such as TF-IDF or BM25. This paper shows retrieval can be done with dense embeddings alone, learned by a simple dual encoder from a modest number of question-passage pairs. The dense retriever beats a strong BM25 system by a wide margin on top-20 passage retrieval accuracy. Plugged into a QA pipeline, it sets new state-of-the-art results on several open-domain benchmarks.', 0.6, 'Retrieval', 'The retriever you would most likely start from.'),
    P('d9', 'ReAct: Synergizing Reasoning and Acting in Language Models', 'Shunyu Yao', 2022, 'ICLR', '2210.03629', 'ReAct prompts language models to interleave reasoning traces with task-specific actions. Reasoning helps the model plan, track progress and handle exceptions, while actions let it query external sources such as a Wikipedia API. On question answering and fact verification, this reduces hallucination and error propagation compared with reasoning alone. On interactive decision-making tasks, ReAct outperforms imitation and reinforcement learning methods using only one or two in-context examples.', 0.66, 'Agents & tools', 'A way to interleave retrieval with multi-hop reasoning steps.'),
    P('d10', 'Lost in the Middle: How Language Models Use Long Contexts', 'Nelson F. Liu', 2023, 'TACL', '2307.03172', 'Recent models accept very long inputs, but it is unclear how well they use that context. The authors test multi-document question answering and key-value retrieval while moving the relevant information around the input. Performance is highest when the information sits at the beginning or end, and drops significantly when it is in the middle, even for models built for long contexts. The study proposes new evaluation protocols for long-context models.', 0.78, 'Retrieval', 'Warns that where retrieved evidence sits may matter as much as whether it is retrieved.'),
    P('d11', 'Self-Consistency Improves Chain of Thought Reasoning in Language Models', 'Xuezhi Wang', 2022, 'ICLR', '2203.11171', 'Chain-of-thought prompting usually decodes a single reasoning path greedily. Self-consistency instead samples many diverse reasoning paths and picks the answer that the most paths agree on. The idea rests on the intuition that a hard problem has several ways of reaching the same correct answer. It significantly improves chain-of-thought accuracy across arithmetic and commonsense reasoning benchmarks.', 0.52, 'Reasoning', 'A cheap reliability boost you could add at inference time.'),
    P('d12', 'Distilling Step-by-Step! Outperforming Larger Language Models with Less Training Data and Smaller Model Sizes', 'Cheng-Yu Hsieh', 2023, 'Findings of ACL', '2305.02301', 'Deploying large language models is expensive, and training small task-specific models usually needs lots of labelled data. Distilling step-by-step extracts rationales from a large model and uses them as extra supervision in a multi-task training setup. Small models trained this way outperform both standard fine-tuning and distillation while using less training data. In one benchmark, a 770M-parameter model outperformed a 540B-parameter model using only part of the available data.', 0.88, 'Small models', 'The strongest non-retrieval route to reasoning in small models — your main comparison.'),
  ],
  relations: [
    { a: 'd2', b: 'd8', type: 'uses-method', note: 'RAG uses DPR as its retriever' },
    { a: 'd5', b: 'd2', type: 'extends', note: 'Adds on-demand retrieval and self-critique' },
    { a: 'd4', b: 'd1', type: 'extends', note: 'Adds cross-attention over retrieved chunks' },
    { a: 'd4', b: 'd2', type: 'compares', note: 'Retrieval at pre-training vs. fine-tuning time' },
    { a: 'd11', b: 'd3', type: 'extends', note: 'Samples many chains and votes' },
    { a: 'd9', b: 'd3', type: 'extends', note: 'Interleaves reasoning with search actions' },
    { a: 'd12', b: 'd3', type: 'uses-method', note: 'Distils rationales into small models' },
    { a: 'd6', b: 'd9', type: 'related', note: 'Both let the model call external tools' },
    { a: 'd10', b: 'd2', type: 'contradicts', note: 'More retrieved context can hurt' },
    { a: 'd12', b: 'd7', type: 'related', note: 'Small models trained on reasoning-rich data' },
    { a: 'd5', b: 'd10', type: 'related', note: 'Both ask when retrieved text actually helps' },
  ],
  gaps: [
    { id: 'g0', title: 'Retrieval-aware reasoning in sub-3B models', closeness: 0.93, papers: ['d5', 'd12', 'd7'], detail: 'Self-RAG and step-by-step distillation each help small models, but nothing here combines retrieval-conditioned self-critique with distilled rationales at small scale. That combination is essentially your hypothesis.' },
    { id: 'g1', title: 'Evidence position in multi-hop chains', closeness: 0.74, papers: ['d10', 'd3', 'd11'], detail: 'Lost in the Middle measures single-hop lookups. Whether evidence position degrades each step of a multi-hop reasoning chain — and compounds — is untested.' },
    { id: 'g2', title: 'Knowing when to stop retrieving', closeness: 0.46, papers: ['d9', 'd6', 'd5'], detail: 'ReAct and Toolformer decide when to call a tool, but none offers a calibrated stopping rule. Small models may over-retrieve and drown their own context.' },
    { id: 'g3', title: 'Compute-matched retrieval vs. parameters', closeness: 0.28, papers: ['d4', 'd2', 'd7'], detail: 'RETRO trades parameters for a database at pre-training scale. A fair, compute-matched comparison at fine-tuning time for small models is missing.' },
  ],
};
